static unsigned map_hash(const char, str);
static map_node_t* map_newnode(const char, key, void* value, int vsize);
static int map_bucketidx(map_base_t* m, unsigned hash);
static void map_addnode(map_base_t* m, map_node_t* node);
static int map_resize(map_base_t* m, int nbuckets);
static map_node_t** map_getref(map_base_t* m, const char, key);
void map_deinit_(map_base_t* m);
void* map_get_(map_base_t* m, const char, key);
int map_insert_(map_base_t* m, const char, key, void* value, int vsize);
void map_remove_(map_base_t* m, const char, key);
map_iter_t map_iter_(void);
const char* map_next_(map_base_t* m, map_iter_t* iter);
